### ISSUE TITLE
No issue, just asking for some support if possible

### ISSUE THREAD

**Issue by Winni66** [ardevd/jlrpy#100]
Hi, sorry to contact you directly, but I'm trying to use the JLR API which you posted at postman to get a connection via php in a smarthome tool (called Edomi).

First: as soon as it's working, is it ok for you to spread it in our KNX forum (https://knx-user-forum.de/) for free (I will mention the basis from postman there).
.... deleted because it works now. Didn't know the registering the device will lead to a failure of curl_exec on php -> I don't now where to search for 204, but it doesn't matter, works fine now.

Eivind gave me the hint to contact the developer of WattCat ;). I also tried your app, even I have bought an used F-Type. Your app is working well.

Nevertheless, I have issues with requesting tokens for RDL/RDU/HBLF:
HTTP Status 405 - Method Not Allowed
I cannot figure out what is wrong here :-( Any hint?

best regards

     Winni

**Comment by ardevd** [comment]
The 405 error seems to indicate that your token request does not include the proper authentication. Do you include the user pin in the request? As detailed in the postman documentation.

**Comment by Winni66** [comment]
Thanks a lot for feedback, I restarted coding from scratch, now it works. Seems that anywhere was a typo. Thanks a lot for providing this API at postman. I will close this "issue".
