### ISSUE TITLE
question on trips information

### ISSUE THREAD

**Issue by wawibu** [ardevd/jlrpy#101]
first I would like to thanks for that library ! driving a landrover defender p400e plug-inn and this library is quite useful :)

I have a struggle around the trip information. I can see EV distance but all other EV related information are empty

`{'trips': [{'id': xxxx, 'name': None, 'category': None, 'routeDetails': {'route': None, 'totalWaypoints': 2, 'boundingBox': {'minLongitude': 6.xxx, 'minLatitude': 51.xxx, 'maxLongitude': 6.xxx, 'maxLatitude': 51.xxx}}, 'tripDetails': {'electricalConsumption': None, 'electricalRegeneration': None, 'fuelConsumption': None, 'distance': 6900, 'startOdometer': 1257000, 'startTime': '2022-05-02T16:58:18+0000', 'startPosition': {'latitude': 51.xxx, 'longitude': 6.xx, 'address': 'xxx, Deutschland', 'postalCode': 'xxxx', 'city': 'xxxx', 'region': 'Nordrhein-Westfalen', 'country': 'Deutschland'}, 'endOdometer': 1264000, 'endTime': '2022-05-02T17:11:13+0000', 'endPosition': {'latitude': 51.xxx, 'longitude': 6.xxx, 'address': 'xxx', 'postalCode': 'xxx', 'city': 'xxx', 'region': 'Nordrhein-Westfalen', 'country': 'Deutschland'}, 'totalEcoScore': {'score': 96.0, 'scoreStatus': 'VALID'}, 'throttleEcoScore': {'score': 4.8, 'scoreStatus': 'VALID'}, 'speedEcoScore': {'score': 4.9, 'scoreStatus': 'VALID'}, 'brakeEcoScore': {'score': 5.0, 'scoreStatus': 'VALID'}, 'averageSpeed': 34.0, 'averageFuelConsumption': 0.0, 'averageEnergyConsumption': 0.0, 'energyRegenerated': 0.0, 'averagePHEVFuelConsumption': 0.0, 'evDistance': 6900.0}}]}`

Assume as they are all 0 - there is no way to get that information?
like electricalConsumption , electricalRegeneration , fuelConsumption , averageFuelConsumption , averageEnergyConsumption , energyRegenerated , averagePHEVFuelConsumption

Or I'm doing something wrong?

Thanks

**Comment by ardevd** [comment]
Unfortunately, I have no experience with JLR PHEVs, but does the official Jaguar apps show you the information?

**Comment by wawibu** [comment]
the app shows also no details further then the EV distance. so might be currently looks like that they have the data points ready for further enhancements

**Comment by wawibu** [comment]
What do you mean with UUID?
the usage of this phyton library is quite good described on the first page and any kind of further details in regards to the API could be found when you follow the link to the API documentation

**Comment by ardevd** [comment]
Closing this due to lack of inactivity.
