### ISSUE TITLE
/geocode/reverse returns HTTP error 400

### ISSUE THREAD

**Issue by alandpearson** [ardevd/jlrpy#102]
Hi There,

First great job on this API. It is super useful to be able to get this info from my car into openHab. Super useful and great work.
On trying it though, I notice that /geocode/reverse/   returns 400.
inControl obviously still has this feature as the app shows it, but I wonder has the API changed or is there an error in the documentation ?
Any pointers appreciated and thanks again.

Alan

**Comment by ardevd** [comment]
Hi there and thanks for reporting the issue. It does seem like the API has changed but there is also a bug in jlrpy. However, if you run the request as documented in the API documentation, you should get a 204 response and not 400. I'll put it on my list to investigate but I wont be able to look into it this week.
