### ISSUE TITLE
Force Refresh of Status Data

### ISSUE THREAD

**Issue by smar000** [ardevd/jlrpy#110]
Hi

Many thanks for this library!

I am using it to get data from an I-Pace. One issue I am experiencing is that the 12V battery voltage value (from `get_status()`) returned by the API ordinarily seems to stay fixed and not change over time, regardless of how often I call `get_status()`, e.g. it is fixed at 14.1V. Once the ignition is off, this value should drop to 12.8v, and then gradually decline further over time, but instead I am seeing the same 14.1V even after leaving the car parked overnight. I cannot seem to get an updated value regardless of how often I call `get_status()`.

If I check in WattCat (on its Details page), I initially see the same value as reported by your library. However, if I then do a refresh on WattCat, the value reported in WattCat drops to the 12.8V (or some lower amount). Going back to get_status() with your library now also returns the same 12.8V as WattCat. 

Is there any way to force a refresh using your library in the same way that WattCat seems to do?

**Comment by ardevd** [comment]
Hi. 

A call to `get_health_status()` will trigger a refresh. It's what WattCat does as well.

**Comment by smar000** [comment]
Thanks for that! All working nicely :)
