### ISSUE TITLE
 Some things have stopped working

### ISSUE THREAD

**Issue by anggar-programacion** [ardevd/jlrpy#127]
Hello. I am Angel from Seville Spain and I have a JAG E-PACE

I have not been able to test starting the engine because my car is manual and I think it would not work.

Until now I have used the library to entertain myself and make some easy applications (I am not an expert programmer).
But I have an application that connects my car with a Google Sheet where I keep all the data that I can get from the car.
A few days ago they stopped working but I updated to 1.6 and then to 1.7

Almost everything now works except the function user=c.get_user_info()
that provided me with information about the owner of the vehicle such as middleName lastName or emailAddress
Now it offers me a list with little data and errors.
Have you reported that error? it can be fixed?
Thank you so much.

**Comment by ardevd** [comment]
Thanks for sharing this. I'll look into it.

**Comment by ardevd** [comment]
Fixed with #121

**Comment by anggar-programacion** [comment]
OK thanks
I check it
