### ISSUE TITLE
Increase code reuse

### ISSUE THREAD

**Issue by jskrist** [ardevd/jlrpy#32]
You have written a nice method:
`__open(self, url, headers=None, data=None)`

which should be used inside the methods:
```
__authenticate(self, data=None)
__register_device(self, headers=None):
__login_user(self, headers=None):
get_vehicles(self, headers):
```
instead of duplicating the code.

**Comment by ardevd** [comment]
Totally agree. Thanks for pointing this out.

**Comment by jskrist** [comment]
No problem.  I have a family member who is interested in using this library, so I figured I would give it a quick code review.  I haven't made it through everything yet, but it looks pretty good so far.
