### ISSUE TITLE
HomeAssistant Integration

### ISSUE THREAD

**Issue by Harryjholmes** [ardevd/jlrpy#51]
Hi
Is there any way to integrate this into home assistant.
Thanks
Harry

**Comment by ardevd** [comment]
Hi there. There is no reason why this can't integrate nicely with Home Assistant. However, someone would have to make a Home Assistant Add-on for it I presume.

**Comment by Harryjholmes** [comment]
Making a custom component should be quite simple seeing as it is already written in python.

**Comment by ardevd** [comment]
Indeed! I don't use Home Assistant myself but I reckon it should be fairly trivial to write the add-on. Feel free to do it and submit a pull request ;)

**Comment by Harryjholmes** [comment]
There is already a Volvo on call component which uses wireless car so shouldn’t be too dissimilar.

**Comment by Harryjholmes** [comment]
[
https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/volvooncall](url)

**Comment by ardevd** [comment]
Bear in mind that while both systems use wirelesscar they still have different front ends. That said, it shouldn't be too difficult to port.

**Comment by Harryjholmes** [comment]
For future reference this might help

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/volvooncall/__init__.py

**Comment by rb28z2** [comment]
For anyone curious, I'm working on this as we speak. I've gotten some basic sensor data displayed on home assistant. Next steps are to get preconditioning, lock actuation, and location working. Hopefully I can get those out within the next week or so.

**Comment by Harryjholmes** [comment]
Brilliant!

**Comment by ardevd** [comment]
Awesome. Looking forward to this. Thank you!

**Comment by Harryjholmes** [comment]
Do you need any testing done? @rb28z2

**Comment by rb28z2** [comment]
Not at the moment. Its been a busy few days with final exams and work, but I'm thinking I'll get a PR opened for what I have at the moment. That way at least you can view the status (basically what I have working as of now) of your vehicle and I can work on adding the ability to control it over the next little while.

**Comment by rb28z2** [comment]
A draft PR for anyone interested: https://github.com/home-assistant/home-assistant/pull/24211

**Comment by smar000** [comment]
Thanks @ardevd for this library. I have it working well with a Range Rover Sport.

In case anyone is interested, I have put together an mqtt wrapper around this library. It also supports HomeAssistant/openHAB discovery: [https://github.com/smar000/jlr2mqtt](https://github.com/smar000/jlr2mqtt)

**Comment by zachamato** [comment]
Hey @smar000 I tried using your mqtt wrapper in HA but having trouble getting started. Any chance you can write up how you did it? I installed the MQTT addon to get started, tried running your jlr2mqtt.py script but ran into some errors.

I may try to look into an actual HA custom component like @rb28z2 but not quite sure my python skills will lead me there. I'm sure whatever I come up with will not pass all the code checks that HA requires for a commit.

**Comment by smar000** [comment]
Hi @zachamato 

So as not to swamp this thread, it may be better if you opened an issue on my repo, with details of the errors you are getting. I'll help where I can, but I don't actually use HA (I'm using openHAB, which supports HA mqtt discovery).

**Comment by msp1974** [comment]
Hi all,

I came across this thread looking for a Hass integration for JLR InControl.  It seemed that the efforts to create this integration have stopped and so I have been working on my own version using this great api.  You can find an early version on my github repo [here](https://github.com/msp1974/homeassistant-jlrincontrol).

I am currently adding the services calls and using the 1.3.2 release that is published on pypi (HA downloads its dependencies from there when loading the integration).  However, I want to be able to check the status of a service call (and ensure there is not one already in progress as this causes and error) and need the latest master releasing with the get_services function in it.

Would it be possible to create this release?
Also, happy for any feedback etc on this integration.  Expect to have services done in the next week or so, work time permitting.

**Comment by ardevd** [comment]
I'd be happy to create a new release. I'll take care of it tomorrow. Thanks for the work on a HA integration.

**Comment by ganzewin** [comment]
I'm trying to install but so far without success. I followed the instructions on your page and copied the files to the custom_components\jlrincontrol directory, added the username: and password: in the configuration.yaml file and upon starting receive the following errors;

Component error: jlrincontrol - Integration 'jlrincontrol' not found.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 391, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/jlrincontrol/__init__.py", line 15, in <module>
    import jlrpy
ModuleNotFoundError: No module named 'jlrpy'

Any idea?

**Comment by msp1974** [comment]
Seems its not installing the jlrpy api from pypi. Will have a check in the morning to see why. If you could post issue on the repo page so i can keep track. Thx Mark

**Comment by msp1974** [comment]
> I'd be happy to create a new release. I'll take care of it tomorrow. Thanks for the work on a HA integration.

Thats great. Thanks

**Comment by msp1974** [comment]
@ganzewin I have tweaked the requirements to include the version.  Can you try again.  If it doesn't work, post an issue on my repo and we'll work it out together.

**Comment by MZorzy** [comment]
ohh this is good news :-D
from what "base" you start? (there are a lot ot car integration on HA)

ps
miss "IS_SUNROOF_OPEN" as binary sensor , maybe under windows
there are ODOMETER_METER ODOMETER_MILES and ODOMETER (i think miles or meter as you set on JLR)

your tire pressure are correct? i have 2700 on rrs tdi, but 270 on rrs hst

**Comment by ganzewin** [comment]
YES it is working with this release! 

It shows My i-Pace Info (vehicle info), Windows (status per window), Tire (Status & Pressure) and the Range (for fuel cars)... 

My main purpose for this integration is;

1. To send me a reminder in case the car needs to be charged and i forgot to connect it. Something like (When its after 23 hour, the 'fuel level'<70% and Car is not charging THEN send me a notification)
2. Try to build economic charging schemes in which the car charges only when the sunpanels on my roof are collecting energy
3. ... whatever comes in my mind.. 

I have 2 remarks "electric charge level not visible" and "Service Info unavailable" which i will post on the repo page!

GREAT JOB GUYS... Thank you!

**Comment by ardevd** [comment]
jlrpy v1.3.3 published

**Comment by stefanv84** [comment]
Can you tell something about the way the car communicates with the servers for this API? Is it via SMS? And would it affect the car battery if the parameters are polled every 5 minutes? Apologies if this is explained somewhere already, I could not find it.

**Comment by msp1974** [comment]
The api just queries the jlr servers for data they have. The car will update every so often when stood but then (in the case of my XF) goes into sleep mode after  48 hours. You then have to start it to come out of sleep. The update health status function will request the car to send an update but only when not in sleep. As such, just polling params every 5 mins does not mean that they are the latest status of the car, nor will it ask the car to update. Hope this answers.

**Comment by msp1974** [comment]
> jlrpy v1.3.3 published

Great. Thanks very much.

**Comment by stefanv84** [comment]
Thanks, that’s insightful. Still wondering how the car sends the info to the jlr servers, but that is not related to this api or integration.

Your answer does suggest it would make sense to have a timestamp on the sensors showing the actual update time, or a separate sensor showing the time of last update sent by the car. So you can see if the info might be outdated.

Looking forward to testing this app more but pretty much homebound atm due to corona..

**Comment by msp1974** [comment]
Car has an onboard telematics device so probably 2G/3G connection.  If you see latest v0.3alpha version this now adds last update attribute to vehicle info sensor as well as a number of other goodies.

**Comment by ardevd** [comment]
> Can you tell something about the way the car communicates with the servers for this API? Is it via SMS? And would it affect the car battery if the parameters are polled every 5 minutes? Apologies if this is explained somewhere already, I could not find it.

It works like this: The InControl service communicates with your car using SMS. The service stores the data and serves you that data when you request it. A timestamp is typically included so that you know how old the data is and if you want you can tell the service to get updated data asynchronously from the vehicle. This takes 5-20 seconds provided the vehicle has cellular coverage.

**Comment by moonlitknight** [comment]
I'm looking to report on my car's battery health so I can predict when it will need to be started and run before the battery dies. So far I have been able to extract the following data using the API
```
TU_STATUS_PRIMARY_VOLT : 3.9000000000000004
TU_STATUS_PRIMARY_CHARGE_PERCENT : 70
BATTERY_STATUS : BATTERY_3_4
CLIMATE_STATUS_REMAINING_RUNTIME : 30
TU_STATUS_POWER : MAIN_BATTERY
BATTERY_VOLTAGE : 12.0
```
The only figure that seems to change after a few days is `TU_STATUS_PRIMARY_VOLT` which was `4` a couple of days ago, and is now `3.9`. The `TU_STATUS_PRIMARY_CHARGE_PERCENT` seems to be higher after a long drive, but then doesn't change, so this seems to be the charge percent when last stopped, rather than the current charge percent.
Do you have any idea how I should interpret these figures?

**Comment by ardevd** [comment]
> I'm looking to report on my car's battery health so I can predict when it will need to be started and run before the battery dies. So far I have been able to extract the following data using the API
> ```
> TU_STATUS_PRIMARY_VOLT : 3.9000000000000004
> TU_STATUS_PRIMARY_CHARGE_PERCENT : 70
> BATTERY_STATUS : BATTERY_3_4
> CLIMATE_STATUS_REMAINING_RUNTIME : 30
> TU_STATUS_POWER : MAIN_BATTERY
> BATTERY_VOLTAGE : 12.0
> ```
> The only figure that seems to change after a few days is `TU_STATUS_PRIMARY_VOLT` which was `4` a couple of days ago, and is now `3.9`. The `TU_STATUS_PRIMARY_CHARGE_PERCENT` seems to be higher after a long drive, but then doesn't change, so this seems to be the charge percent when last stopped, rather than the current charge percent.
> Do you have any idea how I should interpret these figures?
> 

This should probably be asked in a separate issue but at any rate... 

The TU_* values are related the the TCU. The TCU has its own battery and that battery is charged from the low voltage battery afaik. 

What exactly are you trying to accomplish?

**Comment by moonlitknight** [comment]
> This should probably be asked in a separate issue but at any rate...
I understand. was reluctant to pollute the issues with a question which isn't strictly to do with the HASS integration.

> The TU_* values are related the the TCU. The TCU has its own battery and that battery is charged from the low voltage battery afaik.
So ironically, this is the value I would expect to remain constant, regardless of the state of the main battery, yet it is the only number which decreases.

> What exactly are you trying to accomplish?
 I'm looking to report on my car's battery health so I can predict when it will need to be started and run before the battery dies. In the old days, the voltage across a fully charged battery would be 12.6V or so, and drop below 12v when depleted. Optimistically I was hoping the JLR API would provide this reading that I could monitor and intervene it it got too low. What I'm seeing is the `BATTERY_VOLTAGE : 12.0` never changes and `TU_STATUS_PRIMARY_CHARGE_PERCENT : 70` remains at whatever value it was at when the car was parked. The only value that decreases over time is `TU_STATUS_PRIMARY_VOLT`.

**Comment by ardevd** [comment]
This repo is for jlrpy, not the Home Assistant integration, so a separate issue would def make more sense. 

For me the `BATTERY_VOLTAGE` value does change over time. I just had a drive yesterday and it's not at 12.9V. Before that it was at 12.2V.

My TCU battery is almost always at 90%. Since the vehicle goes to sleep after 4 days and shuts down the TCU it's rare to see the TCU battery for down much.

**Comment by moonlitknight** [comment]
> For me the `BATTERY_VOLTAGE` value does change over time. I just had a drive yesterday and it's not at 12.9V. Before that it was at 12.2V.
Thanks for this information. It sounds like my problem is a fault with my car for not updating the voltage which might also explain why the battery is so often flat.

**Comment by ardevd** [comment]
If you have an Android device you can use WattCat to monitor this also

**Comment by ardevd** [comment]
I'll close this issue for now considering work on Home Assistant integrations is happening in separate projects.
