### ISSUE TITLE
Start climate preconditioning

### ISSUE THREAD

**Issue by SuperSaf** [ardevd/jlrpy#59]
Is this working currently? 

The other features such as lock unlock horn blink etc work however when attempting to start climate, an error shows.

Spits a load of error lines out and then ends with HTTP Error 403: Forbidden

I noticed I have to put the pin number in to do the other features but don't require it for climate. I know that it authenticates differently for climate but when using the app it does require the pin for climate as well so could this be the issue?

**Comment by ardevd** [comment]
Hi there.

climate preconditioning should work fine and does not require a pin for me. However, I suspect you're not using this with an I-Pace? Perhaps ICE vehicles require a PIN to start the climate? Will it start the engine if you start preconditioning with the mobile app?

**Comment by SuperSaf** [comment]
Hi,

Ah ok I'm using it with a Range Rover and yes it does start the engine when I start climate in the mobile app.

Do you know anyway that I could do this?

**Comment by ardevd** [comment]
That makes sense then. I know starting the engine requires a PIN but since I've developed jlrpy primarily focused on the I-Pace I'm not too familiar with how the API behaves with ICE variants. If you're willing to test I could whip up a branch and see if simply adding support for submitting a PIN when starting preconditioning works for your Range Rover?

**Comment by SuperSaf** [comment]
Absolutely, I’d be happy to test. 

Is there anyway to request a list from the server of what features/options are available for the car? In the event that it isn’t preconditioning and something else? It comes up as ‘Remote Climate - Start Engine’ in the app.

**Comment by ardevd** [comment]
Hmm, then it does sound like it might be a different command altogether. I'll do some more static analysis and see if I can figure it out. I fear the only other option is to get temporary access to an account with an associated ICE vehicle.

**Comment by SuperSaf** [comment]
I've been trying to look through the data I get when requesting vehicle attributes and vehicle status and it comes up as CLIMATE_STATUS.

Quick question - do you have to enter a pin when starting the climate on your app?

**Comment by ardevd** [comment]
@SuperSaf PIN is not necessary when starting the climate in the I-Pace. It doesn't start the car.

I'm willing to bet the ICE climate preconditioning is totally separate from the EV equivalent judging from how the API works. 

Its probably trivial to implement but it's hard without access to account with a car.

**Comment by Mmodarre** [comment]
I-Pace is different with other Jags and RR models. They required Authentication of REON service and endpoint is /engineOn.

I am planning to add the functionalities as soon as I get sometime to this fantastic library :)

**Comment by ardevd** [comment]
Hi there.

Actually, starting climate preconditioning requires an ECC service token.
Something which jlrpy sorts out for you automatically.

**Comment by ardevd** [comment]
I realize not that you meant that non I-Pace vehicles require the REON service.

**Comment by mattnewham** [comment]
> I-Pace is different with other Jags and RR models. They required Authentication of REON service and endpoint is /engineOn.
> 
> I am planning to add the functionalities as soon as I get sometime to this fantastic library :)

Hey did you get anywhere with this, or have any further information on how to start non I-Pace vehicles?

**Comment by mattnewham** [comment]
@ardevd if you are interested in adding preconditioning for non I-Pace vehicles I'm willing to help by providing access to my vehicle account

**Comment by ardevd** [comment]
@ardevd Sure! I'll need to make jlrpy aware of whether the vehicle is an EV before implementing the logic. If I can record the API requests I can add climate preconditioning for non EVs in the not too distant future I'm sure.

**Comment by mattnewham** [comment]
> @ardevd Sure! I'll need to make jlrpy aware of whether the vehicle is an EV before implementing the logic. If I can record the API requests I can add climate preconditioning for non EVs in the not too distant future I'm sure.

Fabulous just let me know what you need from me. I've been helping @rb28z2 with testing the HomeAssistant component, which looks like it might be accepted upstream so the next step would be adding the additional functionality like preconditioning etc

**Comment by ardevd** [comment]
@mattnewham Really cool that you're helping out with the home assistant integration. I'm waiting for that one myself :) 

If you could chime in on Gitter then I could PM you there for further details?

**Comment by zachamato** [comment]
@mattnewham @ardevd I was able to successfully start my 2019 RR Velar by authenticating the **REON** service, and using the **/engineOn** endpoint. I will test later to see if I can successfully set the target temperature.

I shut off the vehicle by authenticating the **REOFF** service and posting that token to **/engineOff**. The iOS app does report say there was a "Remote Climate" error after I send that command.

I am wondering if that has anything to do with the headers or service parameters I was sending:

```POST /if9/jlr/vehicles/{{vin}}/engineOn HTTP/1.1
Host: if9.prod-row.jlrmotor.com
Content-Type: application/vnd.wirelesscar.ngtp.if9.StartServiceConfiguration-v2+json
X-Device-Id: {{device_id}}

{
	"token": "{{reon_token}}",
	"serviceParameters":[{
		"key":"ClimateControlRccTargetTemp",
		"value":"210"
		}]
}

POST /if9/jlr/vehicles/{{vin}}/engineOff HTTP/1.1
Host: if9.prod-row.jlrmotor.com
Content-Type: application/vnd.wirelesscar.ngtp.if9.StartServiceConfiguration-v2+json
X-Device-Id: {{device_id}}

{
	"token": "{{reoff_token}}"
}```

**Comment by zachamato** [comment]
I realize now that `ClimateControlRccTargetTemp` is likely the "Rear Climate Control" feature.

**Comment by ardevd** [comment]
Interesting. Again, I have no ICE JLR vehicle to test with. Otherwise I would just do some dynamic analysis with the official app and figure it out :)

Good luck and thanks for sharing your findings.

**Comment by zachamato** [comment]
Understood, I tried to intercept and read the packets from the iOS app but it uses SSL pinning and the app would crash when I tried to setup Proxyman/Wireshark.

I'd be willing to reset my credentials and allow you to test on my vehicle... at a coordinated time obviously. Not sure I have the technical knowledge to dig very deep into this. I will try to look into it more on my own as I have some down time at work this week.

**Comment by ardevd** [comment]
@zachamato Sure. Let me know and I'll be happy to help you out :)

**Comment by zachamato** [comment]
Ok got this figured out using Proxyman and a jailbroken iPhone (SSL Pinning/Jailbreak Detection disabled), next step would be adding the code and updating the postman collection. I also use HomeAssistant so my end goal for this would be HomeAssistant > HomeKit/Siri/Alexa to start my car.

### ClimateControlRccTargetTemp

31 is Low 57 is HI _(26 total increments between. These do not seem to match any Celsius or Fahrenheit numbers)._

**/vehicles/{{vin}}/settings**
`POST
Header:
Content-Type: application/json;charset=UTF-8
Body:
{"key":"ClimateControlRccTargetTemp","value":"{{target_temp_celsius}}","applied":1}`

### Remote Engine Start
**REON Service:**
`POST
Header:
Content-Type: application/vnd.wirelesscar.ngtp.if9.AuthenticateRequest-v2+json
Body:
{"serviceName":"REON","pin":"1234"}`

**/vehicles/{{vin}}/engineOn**
`POST
Header:
Content-Type: Content-Type: application/vnd.wirelesscar.ngtp.if9.StartServiceConfiguration-v3+json
Accept: Accept: application/vnd.wirelesscar.ngtp.if9.ServiceStatus-v4+json
Body:
{"token":"{{reon_token}}"}`

### Remote Engine Stop
**REOFF Service:**
`POST
Header:
Content-Type: application/vnd.wirelesscar.ngtp.if9.AuthenticateRequest-v2+json
Body:
{"serviceName":"REOFF","pin":"1234"}`

**/vehicles/{{vin}}/engineOff**
`POST
Header:
Content-Type: Content-Type: application/vnd.wirelesscar.ngtp.if9.StartServiceConfiguration-v3+json
Accept: Accept: application/vnd.wirelesscar.ngtp.if9.ServiceStatus-v4+json
Body:
{"token":"{{reoff_token}}"}`

**Comment by smar000** [comment]
Thanks for the recent merge on this. 

Is there any way to check whether the engine is currently on/off? I see the `alert_engine_on`, but this doesn't seem to update when the engine has been turned off.

**Comment by zachamato** [comment]
@smar000 You could send the command to turn the engine off... then poll the service status to see if it was successful. I do not think there is an alert for `engine_off` under vehicle status.

**Comment by smar000** [comment]
Thanks, will try that.

**Comment by smar000** [comment]
Has anyone worked out if it is possible to also remotely start seat heating (I know the InControl app doesn't seem to have an option for this)?

**Comment by mattnewham** [comment]
There isn’t. You can see all the endpoints in the guide.

If it’s not in the app it’s not a thing. Why would you need it anyway seats
heat up in less than a minute anyway

**Comment by ardevd** [comment]
> Thanks for the recent merge on this.
> 
> Is there any way to check whether the engine is currently on/off? I see the `engine_on` under `vehicleAlerts`, but this doesn't seem to update when the engine has been turned off.

Yes! Check the `VEHICLE_STATE_TYPE` status value.

```python
v.get_status("v.get_status("VEHICLE_STATE_TYPE")
```
If it shows `KEY_REMOVED` or `KEY_ON_ENGINE_OFF` then the engine should be off.

**Comment by smar000** [comment]
> There isn’t. You can see all the endpoints in the guide. If it’s not in the app it’s not a thing. Why would you need it anyway seats heat up in less than a minute anyway
Thanks and yes, whilst they do heat up reasonably quickly I was just wondering whether pre-heating the seats was available as part of the overall climate control/preconditioning. 

> > Is there any way to check whether the engine is currently on/off? I see the `engine_on` under `vehicleAlerts`, but this doesn't seem to update when the engine has been turned off.
> 
> Yes! Check the `VEHICLE_STATE_TYPE` status value.
Great, thanks!

**Comment by ardevd** [comment]
Ill close this issue now since the original question has been resolved.
