### ISSUE TITLE
Charging load input

### ISSUE THREAD

**Issue by Lasmu** [ardevd/jlrpy#65]
Hello,
thx for the script.
do you think to control the charging power outside?
issue to follow recent photovoltaic power?

Thx, for your answer

**Comment by ardevd** [comment]
Hi there. I'm not quite sure I follow. Are you asking whether it could be possible to control charging power using the API?

**Comment by Lasmu** [comment]
Hello. Sorry for my bad english. Yes i would like to control the charging power over the api. Is it possible?

**Comment by ardevd** [comment]
Unfortunately the API provides no such feature at this time.

**Comment by Lasmu** [comment]
okay, thx for the fast answer.

Have a nice day.
