### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by olemr** [ardevd/jlrpy#70]
First of all, thank you for this great library!
I'm struggling understanding the concept of refresh tokens.
Could you shed some light on the subject, please?

**Comment by ardevd** [comment]
The use of refresh tokens is pretty common in REST APIs. You can read more about them [here](https://auth0.com/learn/refresh-tokens/)

**Comment by olemr** [comment]
Read that link and I'm familiar with REST API tokens.
I just fail to realise how to obtain it.
A _print(c.refresh_token)_ showed me the light.
Thanks.
