### ISSUE TITLE
PostMan API documentation - possible issues found to date

### ISSUE THREAD

**Issue by gtboswood** [ardevd/jlrpy#72]
The only real problem is the first one but it wasn't too hard to figure out.  The others are just observations/suggestions.

Problem
Login user and all remaining commands after the initial authorization sequence require the presence of the access token in the header:  'Authorization: Bearer {{access_token}}'.  You do mention that the access token is needed in your "device registration" section, it is just missing in the curl examples and header descriptions.  There was also no mention that the word "Bearer" (followed by a space) is required before the access token.

Suggestions
1. Login user does not need 'Connection: close' in the header although it causes no harm.  I only experimented with removing this as part of diagnosing another problem with my code but ended up observing it was fine either way.
2. The empty data response in device registration wasn't really expected and maybe should be noted but not a big deal.  You did note that the proper response to look for was a 204 status.
3. The use of primary_only in 'get vehicles' led me to expect a single response but it is still a list but with just one entry.  Another small thing but might be worth noting.

**Comment by ardevd** [comment]
Thank you for taking the time to report the issues. I'll look over it and update the documentation.

**Comment by ardevd** [comment]
That doc's do state the following:

> The access token must be included in all subsequent requests as the Authorization bearer in the HTTP header.

But I agree that it would be nice to include it in the curl examples.

**Comment by ardevd** [comment]
1, 2 and 3 have been fixed. Thank you again.
