### ISSUE TITLE
Homebridge plugin

### ISSUE THREAD

**Issue by allanjeevan** [ardevd/jlrpy#85]
Could you make a homebridge plugin with this, as i tried a plugin but it dosent remote start the car.

**Comment by ardevd** [comment]
Unfortunately, I doubt I'll find the time to develop a Homebridge plugin.

**Comment by allanjeevan** [comment]
Sure thanks for letting me know.

**Comment by william-cowell-mf** [comment]
You could try this one: [homebridge-jlr-incontrol](https://www.npmjs.com/package/homebridge-jlr-incontrol)
It's been recently updated to align it with changes to the underlying API. It doesn't support starting the car, but you're welcome to submit a PR!

**Comment by ardevd** [comment]
Closing this issue as it seems a homebridge plugin exists or is at least under development.
