### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by aarons2222** [ardevd/jlrpy#87]
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    import jlrpy
  File "/Users/macmini/Library/Python/2.7/lib/python/site-packages/jlrpy.py", line 5, in <module>
    from urllib.request import Request, build_opener
ImportError: No module named request

**Comment by ardevd** [comment]
Hi there.

`jlrpy` supports python3 only I'm afraid. You're using 2.7.

**Comment by aarons2222** [comment]
Same error, even with Python3!

**Comment by ardevd** [comment]
What specific Python version are you using and on what operating system?

**Comment by ardevd** [comment]
Closing this due to lack of updates. Feel free to reach out if you're still having isssues.
