### ISSUE TITLE
Info about installed Software version

### ISSUE THREAD

**Issue by ismarslomic** [ardevd/jlrpy#96]
Thanks for very nice lib for retrieving data from my I-Pace! 

Just wondering if there are any data available about currently installed software version(s)?

**Comment by ismarslomic** [comment]
Right, I have seen the version data for `TU_STATUS_SW_VERSION_MAIN` (which is the only software version field), which for my car is `L8B2-70712-AX`. How does this map to the readable equivalents you are referring to (what is the mapping logic)?

**Comment by ardevd** [comment]
I havent seen that value before I'm afraid. Its also region specific so I only have the most common ones nailed down tbh.

```java
 @Nullable
     public static String getAlternateTcuVersion(String tcuVersion) {
         switch (tcuVersion) {
             case "J8A2-70712-AS":
                 return "14.2";
             case "J8A2-70712-AT":
             case "J9C3-70712-AT":
                 return "15.2";
             case "J8A2-70712-AV":
             case "J9C3-70712-AV":
                 return "16.2";
             case "J8A2-70712-AX":
                 return "17.2";
             case "J8A2-70712-AY":
             case "J9C3-70712-AY":
                 return "18.2";
             case "J8A2-70712-AZ":
                 return "19.2";
             default:
                 return null;
         }
}
````

**Comment by ismarslomic** [comment]
Anywhere I can find these translation documented?

**Comment by ardevd** [comment]
What do you mean exactly?

**Comment by ismarslomic** [comment]
How did you find out that for instance `J8A2-70712-AS` maps to `14.2`? Where these mapping rules documented somewhere?

**Comment by ardevd** [comment]
The mapping rules are the result of surveys I did on various owner forums, so it's not based on any official documentation (there is no such thing) but rather community reported data.

**Comment by ardevd** [comment]
I'll close this for now. Feel free to open a new one if you have more questions.

Cheers
